#!/usr/bin/env python3

import sys
import requests
import json

from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class issue(QWidget):
    def __init__(self):
        super().__init__()
        self.title = ""
        self.issue_number = 0
        self.created_at = 0

class main_window(QWidget):
    def __init__(self):
        super().__init__()

        # Add layout to the window to set items
        layout = QHBoxLayout(self)
        VB = QVBoxLayout(self)
        layout.addLayout(VB)

        # Get the URL of issues and turn it from JSON to dictionary
        url = "https://api.github.com/repos/walmartlabs/thorax/issues"
        content = requests.get(url)
        issue_list = json.loads(content.content)

        print(issue_list)




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = main_window()
    w.setGeometry(500, 300, 800, 600)
    w.show()
    sys.exit(app.exec_())
